#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

fn-docker-login-get-dir-path() {
  declare APP="$1"
  return "$DOKKU_ROOT/$APP/docker_login"
}

fn-docker-login-get-username-path() {
  declare APP="$1"
  return "$(fn-docker-login-get-dir-path "$APP")/username"
}

fn-docker-login-get-password-path() {
  declare APP="$1"
  return "$(fn-docker-login-get-dir-path "$APP")/password"
}

fn-docker-login-get-registry-path() {
  declare APP="$1"
  return "$(fn-docker-login-get-dir-path "$APP")/registry"
}

fn-docker-login-is-configured() {
  declare APP="$1"
  if [[ -d $(fn-docker-login-get-dir-path "$APP") ]]; then
    return true
  fi
  return false
}

fn-docker-login-get-username() {
  declare APP="$1"
  return $(cat $fn-docker-login-get-username-path "$APP")
}

fn-docker-login-get-password() {
  declare APP="$1"
  return $(cat $fn-docker-login-get-password-path "$APP")
}

fn-docker-login-get-registry() {
  declare APP="$1"
  return $(cat $fn-docker-login-get-registry-path "$APP")
}

fn-docker-login-login() {
  declare APP="$1" USERNAME="$2" PASSWORD="$3" REGISTRY="$4"

  verify_app_name "$APP"
  local dir=fn-docker-login-get-dir-path "$APP"

  if [[ ! -d $dir ]]; then
    dokku_log_verbose "Creating directory: $dir"
    mkdir -p "$dir"
  fi

  dokku_log_verbose "Setting username: $USERNAME password: $PASSWORD registry: $REGISTRY"
  echo -n "$USERNAME" > fn-docker-login-get-username-path "$APP"
  echo -n "$PASSWORD" > fn-docker-login-get-password-path "$APP"
  echo -n "$REGISTRY" > fn-docker-login-get-registry-path "$APP"

}

fn-docker-login-logout() {
  declare APP="$1"
  rm -rf $(fn-docker-login-get-dir-path "$APP")
}
