#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

fn-docker-login-get-dir-path() {
  declare APP="$1"
  echo -n "$DOKKU_ROOT/$APP/docker_login"
}

fn-docker-login-get-username-path() {
  declare APP="$1"
  echo -n "$(fn-docker-login-get-dir-path "$APP")/username"
}

fn-docker-login-get-password-path() {
  declare APP="$1"
  echo -n "$(fn-docker-login-get-dir-path "$APP")/password"
}

fn-docker-login-get-registry-path() {
  declare APP="$1"
  echo -n "$(fn-docker-login-get-dir-path "$APP")/registry"
}

fn-docker-login-is-configured() {
  declare APP="$1"
  if [[ -d $(fn-docker-login-get-dir-path "$APP") ]]; then
    echo -n "true"
  else
    echo -n "false"
  fi
}

fn-docker-login-get-username() {
  declare APP="$1"
  cat $(fn-docker-login-get-username-path "$APP")
}

fn-docker-login-get-password() {
  declare APP="$1"
  cat $(fn-docker-login-get-password-path "$APP")
}

fn-docker-login-get-registry() {
  declare APP="$1"
  cat $(fn-docker-login-get-registry-path "$APP")
}

fn-docker-login-set() {
  declare APP="$1" USERNAME="$2" PASSWORD="$3" REGISTRY="$4"

  verify_app_name "$APP"
  local dir=$(fn-docker-login-get-dir-path "$APP")

  if [[ ! -d $dir ]]; then
    dokku_log_verbose "Creating directory: $dir"
    mkdir -p "$dir"
  fi

  dokku_log_verbose "Setting username: $USERNAME password: $PASSWORD registry: $REGISTRY"
  echo -n "$USERNAME" > $(fn-docker-login-get-username-path "$APP")
  echo -n "$PASSWORD" > $(fn-docker-login-get-password-path "$APP")
  echo -n "$REGISTRY" > $(fn-docker-login-get-registry-path "$APP")
}

fn-docker-login-reset() {
  declare APP="$1"
  rm -rf $(fn-docker-login-get-dir-path "$APP")
}

fn-docker-login-logout() {
  declare APP="$1"

  if [[ $(fn-docker-login-is-configured "$APP") == "true" ]]; then
    local registry=$(fn-docker-login-get-registry)
    dokku_log_verbose "Logging out of docker registry: $registry"
    $DOCKER_BIN logout "$registry"
  fi
}

fn-docker-login-login() {
  declare APP="$1"

  if [[ $(fn-docker-login-is-configured "$APP") == "true" ]]; then
    local username=$(fn-docker-login-get-username "$APP")
    local password=$(fn-docker-login-get-password "$APP")
    local registry=$(fn-docker-login-get-registry "$APP")

    dokku_log_verbose "Logging into docker registry: $registry with username: $username"
    echo -n "$password" | $DOCKER_BIN login --username "$username" --password-stdin "$registry"
  fi
}
