#!/usr/bin/env bash
source "$PLUGIN_AVAILABLE_PATH/docker-login/internal-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-docker-login-post-build-dockerfile() {
  declare desc="post build dockerfile"
  declare trigger="post-build-dockerfile"
  declare APP="$1"

  fn-docker-login-logout "$APP"
}

trigger-docker-login-post-build-dockerfile "$@"
