#!/usr/bin/env bash
source "$PLUGIN_AVAILABLE_PATH/docker-login/internal-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-docker-login-pre-build-dockerfile() {
  declare desc="pre build dockerfile"
  declare trigger="pre-build-dockerfile"
  declare APP="$1"

  fn-docker-login-login "$APP"
}

trigger-docker-login-pre-build-dockerfile "$@"
